### ISSUE TITLE
Required fields are missing

### ISSUE THREAD

**Issue by jimmyyem** [aliyun/aliyun-log-php-sdk#44]
PHP8.0 
Macos 
Laravel9.33 
alibabacloud/aliyun-log-php-sdk:0.6.3

具体错误调用栈：
#0 /data/api/vendor/alibabacloud/aliyun-log-php-sdk/Aliyun/Log/sls.proto.php(191): Log_Content->write(Resource id #8)
#1 /data/api/vendor/alibabacloud/aliyun-log-php-sdk/Aliyun/Log/sls.proto.php(335): Log->write(Resource id #8)
#2 /data/api/vendor/alibabacloud/aliyun-log-php-sdk/Aliyun/Log/Util.php(62): LogGroup->write(Resource id #8)
#3 /data/api/vendor/alibabacloud/aliyun-log-php-sdk/Aliyun/Log/Client.php(258): Aliyun_Log_Util::toBytes(Object(LogGroup))
#4 /data/api/app/Lib/AliLog.php(69): Aliyun_Log_Client->putLogs(Object(Aliyun_Log_Models_PutLogsRequest))
#5 /data/api/app/Http/Controllers/Api/SentryController.php(59): App\Lib\AliLog->write('Uncaught Refere...')
#6 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\SentryController->report(O ▶
#7 /data/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction ▶
#8 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Objec ▶
#9 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#10 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#11 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{clo ▶
#12 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->I ▶
#13 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-> ▶
#14 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline->Il ▶
#15 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\Th ▶
#16 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\Thr ▶
#17 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests->ha ▶
#18 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\ ▶
#19 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack(Object ▶
#21 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute(Object(Illuminate ▶
#22 /data/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Ill ▶
#23 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Il ▶
#24 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foun ▶
#25 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipe ▶
#26 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Found ▶
#27 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmpty ▶
#28 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipe ▶
#29 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Mid ▶
#30 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings- ▶
#31 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipel ▶
#32 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePost ▶
#33 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminat ▶
#34 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventReque ▶
#35 /data/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\P ▶
#36 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle(Obje ▶
#37 /data/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate ▶
#38 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Ob ▶
#39 /data/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\ ▶
#40 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Clo ▶
#41 /data/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendReques ▶
#42 /data/api/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}

**Comment by Tiacx** [comment]
LogItem 的数组内容里不能有 null 值，例如：`['user_id' => '']` √  `['user_id' => null]` ×。今天刚解决完这个问题！！
