### ISSUE TITLE
进程卡死，目测是卡在curl

### ISSUE THREAD

**Issue by xcl3721** [aliyun/aliyun-log-php-sdk#6]
#0  0x00007fe0c1462e2d in poll () from /lib64/libc.so.6
#1  0x00007fe0c240f2b9 in Curl_poll () from /lib64/libcurl.so.4
#2  0x00007fe0c24081fd in curl_multi_wait () from /lib64/libcurl.so.4
#3  0x00007fe0c240132f in curl_easy_perform () from /lib64/libcurl.so.4
#4  0x000000000056bef9 in zif_curl_exec (execute_data=<optimized out>, return_value=0x7fe0bd614d20) at /data/download/php-7.1.6/ext/curl/interface.c:3032
#5  0x000000000080f2b6 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /data/download/php-7.1.6/Zend/zend_vm_execute.h:675
#6  0x00000000007ff49b in execute_ex (ex=<optimized out>) at /data/download/php-7.1.6/Zend/zend_vm_execute.h:429
#7  0x00000000007ab361 in zend_call_function (fci=fci@entry=0x7ffe64ebb080, fci_cache=0x7ffe64ebafc0, fci_cache@entry=0x0) at /data/download/php-7.1.6/Zend/zend_execute_API.c:855

(gdb) zbacktrace
[0x7fe0bd614e50] curl_exec(resource(#-1117430832)) [internal function]
[0x7fe0bd614c60] RequestCore->send_request() /data/webroot/shuangshi/release/plugin/Aliyun/Log/requestcore.class.php:817 
[0x7fe0bd614a30] Aliyun_Log_Client->getHttpResponse("GET", "http://shuangshi.cn-beijing.log.aliyuncs.com:80/logstores/doubleteacher_analytics_java/shards", NULL, array(8)[0x7fe0bd614ab0]) /data/webroot/shuangshi/release/plugin/Aliyun/Log/Client.php:141 
[0x7fe0bd614720] Aliyun_Log_Client->sendRequest("GET", "http://shuangshi.cn-beijing.log.aliyuncs.com:80/logstores/doubleteacher_analytics_java/shards", NULL, array(8)[0x7fe0bd6147a0]) /data/webroot/shuangshi/release/plugin/Aliyun/Log/Client.php:156 
[0x7fe0bd614290] Aliyun_Log_Client->send("GET", "shuangshi", NULL, "/logstores/doubleteacher_analytics_java/shards", array(0)[0x7fe0bd614320], array(8)[0x7fe0bd614330]) /data/webroot/shuangshi/release/plugin/Aliyun/Log/Client.php:219 
[0x7fe0bd613ff0] Aliyun_Log_Client->listShards(object[0x7fe0bd614040]) /data/webroot/shuangshi/release/plugin/Aliyun/Log/Client.php:543 
[0x7fe0bd613ac0] Interaction->checkAllProcess() /data/webroot/shuangshi/release/daemon/aliyunpulllog/src/core/pull/Interaction.php:142 
[0x7fe0bd6135b0] LogMonitor->monitor(object[0x7fe0bd613600]) /data/webroot/shuangshi/release/daemon/aliyunpulllog/src/logmonitor.php:220 

卡死了，

**Comment by shizishizi2012** [comment]
请问最后如何解决该问题的？

**Comment by archdesigner** [comment]
> 请问最后如何解决该问题的？

这个问题已经解决了，升级下libcurl尽量用新版本，sdk的composer升级下版本，然后底层实际上对keep alive时间改短了
